### ISSUE TITLE
New to gdextension, how do I use this in godot?

### ISSUE THREAD

**Issue by Just-Jasmine** [Hapenia-Lans/gdextension-nim#1]
Hi! I'm new to programming, so I have no clue on how to use this. I tried doing "nake gen" in the git directory, but godot still complains when it loads the test project. How to use this in godot? Also, we should add it to the readme so no one makes the same mistakes I did! Thank you for your time and making this awesome project!

**Comment by hapenia** [comment]
This project is still in a very early state and I'm still working on how gdextension works through Godot-CPP. Now, it can simply run successfully using the original features of the nim. Interaction with Godot is still being processed.

**Comment by hapenia** [comment]
I improved project structure so that you can run `nake build` in `testgde`, then godot will find the dynlib correctly. I work in linux, so I don't know if this could be done in windows or mac.

**Comment by Just-Jasmine** [comment]
That should work, thank you so much for taking the time to help! Do you have a discord or another way of getting in contact? I'd love to be able to learn what I can about nim and eventually help with this project!

**Comment by Just-Jasmine** [comment]
Unfortunately when I run `nake build` in the tests/testgde directory on my manjaro install it tells me that the only available task is `nake gen`

`~/Documents/gdextension-nim/tests/testgde> nake build`                                                                                                                                         
`Task 'build' not found.`
`Available tasks:`
`gen - Generate bindings`

**Comment by hapenia** [comment]
> Do you have a discord or another way of getting in contact?

Yes, user name Hapenia#8221.

> Unfortunately when I run nake build in the tests/testgde directory on my manjaro install it tells me that the only available task is nake gen

Please open `nakefile.nim` with your code editor to see whether it has a `build` task or not. If not, `git pull` maybe fix it. If there still are some magic errors occurs there, you can simply copy these code to replace the content of  your `nakefile.nim`:

```nim
import nake;
import strformat;

const
  GodotProjectPath = "../testproj"
  GeneratedBinDirName = "bin"
  Entry = "src/testgde"


task "gen", "generate binding":
  #todo: add bindgen
  discard

task "build", "compile your nim extension into dynamic library.":
  # discard execShellCmd fmt"nim c {Entry} --mm:orc --app:lib -o:" & GodotProjectPath/DynlibName
  shell fmt"nim c --mm:orc --app:lib --outdir:{GodotProjectPath/GeneratedBinDirName} {Entry}"

```

**Comment by Just-Jasmine** [comment]
Hey, I added you on discord! We definitely made some progress, but I'm still a little lost. I pulled the new and improved nake file, and it's giving me an error still, albeit a different one. I added the folder of godot 4 to my path, and renamed the executable "godot." I even made a copy of that executable and added it to the root of the project.

```
~/Documents/gdextension-nim/tests/testgde> nake build                                                                                                                                                          
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
.........................................................
/home/just0jasmine/Documents/gdextension-nim/tests/testgde/src/testgde.nim(1, 30) Error: cannot open file: gdextension_nim/godot
```
