### ISSUE TITLE
MacOS: Unable to load extension

### ISSUE THREAD

**Issue by ShalokShalom** [Hapenia-Lans/gdextension-nim#3]
This is what I get in macOS, when I follow the instructions:

<img width="1440" alt="Bildschirmfoto 2022-10-31 um 12 14 07" src="https://user-images.githubusercontent.com/6344099/198995492-356b4bb2-f3ee-4dff-9969-1c7935edac97.png">

I am usually not a macOS guy, and launching Godot from Terminal with open -a Godot 4.app does give me a prompt and no error messages.

So idk how to give the best feedback.

**Comment by curioussavage** [comment]
I was able to get godot to load the shared library by doing the following:

In the godot project the file that points to the shared lib (in this case named `nim.gdextension`) should have an appropriate path added for the architecture. In this case we should modify it to add:

```nim
[configuration]

entry_symbol = "exampleLibraryInit"

[libraries]

linux.64.debug = "bin/libtestgde.so"
windows.64.debug = "bin/libtestgde.dll"
macos.arm64 = "bin/libtestgde.dylib"
```

Next if nim was installed using choosenim (meaning we have the amd64 binary we will need to make sure we build for arm64. If `nim --version` has arm64 in the first line of output then you don't need to bother with this step.

in this case the most basic change to the nakefile.nim could look like:


```nim
import nake;
import strformat;

const
  GodotProjectPath = "../testproj"
  GeneratedBinDirName = "bin"
  Entry = "src/testgde"
  ArmFlags = "-l:'-target arm64-apple-macos11' -t:'-target arm64-apple-macos11'"



task "gen", "generate binding":
  #todo: add bindgen
  discard

task "build", "compile your nim extension into dynamic library.":
  # discard execShellCmd fmt"nim c {Entry} --mm:orc --app:lib -o:" & GodotProjectPath/DynlibName
  shell fmt"nim c --mm:orc --app:lib {ArmFlags}  --outdir:{GodotProjectPath/GeneratedBinDirName} {Entry}"
```

**Comment by ShalokShalom** [comment]
Thanks a lot for fixing this!

It has appeared to me, that this repo is effectively abandoned, sadly.

Your arm comments hint, that you are using and meaning the M1 and M2 devices.

**Comment by Angluca** [comment]
I has use more cmd test, But cant loading or crash T_T lib in macos 11+, godot 4,
 ArmFlags = "-l:'-target arm64-apple-macos11' -t:'-target arm64-apple-macos11'"
 ArmFlags = "-l:'-target x86_64-apple-macos11' -t:'-target x86_64-apple-macos11'"
macos = ...
macos.debug = ...
macos.arm64 = ...

**Comment by ShalokShalom** [comment]
This project is effectively dead. 
https://github.com/Hapenia-Lans/gdextension-nim/issues/2#issuecomment-1318076842
